### ISSUE TITLE
Coordinating efforts

### ISSUE THREAD

**Issue by 1602** [arnau/elm-feather#1]
I created https://1602.github.io/elm-feather-icons/ for my work needs (in order to generate elm from SVG for selected subset of feather icons).

Then some folks asked me to create a lib, which I did: https://github.com/1602/elm-feather
Then other folks [found](https://github.com/1602/elm-feather/issues/5) that [similar](http://package.elm-lang.org/packages/arnau/elm-feather/latest) package already exists.

So, I just wanted to say hello here, since we're using our module in production and have some additional API, I'm going to continue maintaining library I created. If you have any thoughts regarding further coordination of efforts please don't hesitate to contact me.

**Comment by arnau** [comment]
Hey, sorry for the late response! I think your codebase is much more mature than mine. And given that you are using it in production and I don't, I'm more than happy to make mine obsolete and redirect to yours.

**Comment by 1602** [comment]
No worries, thanks @arnau!
